
package arayuz;

import javax.swing.JOptionPane;
import ekPaket.*;
import java.sql.*;
import tablolar.Mudur;
import tablolar.Musteri;
import tablolar.Temsilci;

/**
 *
 * @author 90543
 */
public class girisGUI extends javax.swing.JFrame {

    /**
     * Creates new form girisGUI
     */
    private DataBaseBaglanti conn = new DataBaseBaglanti();
    
    public girisGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabbed_p = new javax.swing.JTabbedPane();
        pnl_musteri_giris = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fld_musteri_tc_giris = new javax.swing.JTextField();
        fld_musteri_sifre_giris = new javax.swing.JPasswordField();
        btn_musteri_giris = new javax.swing.JButton();
        pnl_temsilci_giris = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fld_temsilci_tc_giris = new javax.swing.JTextField();
        fld_temsilci_sifre_giris1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        btn_temsilci_giris = new javax.swing.JButton();
        pnl_mudur_giris = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        fld_mudur_tc_giris = new javax.swing.JTextField();
        fld_mudur_sifre_giris = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        btn_mudur_giris = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banka Giris Ekrani");
        setLocation(new java.awt.Point(400, 200));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        pnl_musteri_giris.setBackground(new java.awt.Color(51, 255, 51));

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel1.setText("TC Numariniz :");

        jLabel2.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel2.setText("Sifreniz :");

        btn_musteri_giris.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_musteri_giris.setText("Giris");
        btn_musteri_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_musteri_girisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_musteri_girisLayout = new javax.swing.GroupLayout(pnl_musteri_giris);
        pnl_musteri_giris.setLayout(pnl_musteri_girisLayout);
        pnl_musteri_girisLayout.setHorizontalGroup(
            pnl_musteri_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_musteri_girisLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(pnl_musteri_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_musteri_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_musteri_girisLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(60, 60, 60)
                        .addComponent(fld_musteri_tc_giris))
                    .addGroup(pnl_musteri_girisLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(110, 110, 110)
                        .addComponent(fld_musteri_sifre_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        pnl_musteri_girisLayout.setVerticalGroup(
            pnl_musteri_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_musteri_girisLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(pnl_musteri_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fld_musteri_tc_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_musteri_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(fld_musteri_sifre_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btn_musteri_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        tabbed_p.addTab("Musteri Girisi", pnl_musteri_giris);

        pnl_temsilci_giris.setBackground(new java.awt.Color(204, 255, 51));

        jLabel4.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel4.setText("TC Numariniz :");

        jLabel5.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel5.setText("Sifreniz :");

        btn_temsilci_giris.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_temsilci_giris.setText("Giris");
        btn_temsilci_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_temsilci_girisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_temsilci_girisLayout = new javax.swing.GroupLayout(pnl_temsilci_giris);
        pnl_temsilci_giris.setLayout(pnl_temsilci_girisLayout);
        pnl_temsilci_girisLayout.setHorizontalGroup(
            pnl_temsilci_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_temsilci_girisLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(pnl_temsilci_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(pnl_temsilci_girisLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(60, 60, 60)
                        .addComponent(fld_temsilci_tc_giris))
                    .addGroup(pnl_temsilci_girisLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(110, 110, 110)
                        .addComponent(fld_temsilci_sifre_giris1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_temsilci_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );
        pnl_temsilci_girisLayout.setVerticalGroup(
            pnl_temsilci_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_temsilci_girisLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnl_temsilci_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fld_temsilci_tc_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_temsilci_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(fld_temsilci_sifre_giris1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btn_temsilci_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        tabbed_p.addTab("Temsilci Girisi", pnl_temsilci_giris);

        pnl_mudur_giris.setBackground(new java.awt.Color(51, 255, 204));

        jLabel6.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel6.setText("TC Numariniz :");

        jLabel7.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel7.setText("Sifreniz :");

        btn_mudur_giris.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_mudur_giris.setText("Giris");
        btn_mudur_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mudur_girisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_mudur_girisLayout = new javax.swing.GroupLayout(pnl_mudur_giris);
        pnl_mudur_giris.setLayout(pnl_mudur_girisLayout);
        pnl_mudur_girisLayout.setHorizontalGroup(
            pnl_mudur_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_mudur_girisLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(pnl_mudur_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(pnl_mudur_girisLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(60, 60, 60)
                        .addComponent(fld_mudur_tc_giris))
                    .addGroup(pnl_mudur_girisLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(110, 110, 110)
                        .addComponent(fld_mudur_sifre_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_mudur_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );
        pnl_mudur_girisLayout.setVerticalGroup(
            pnl_mudur_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_mudur_girisLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnl_mudur_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fld_mudur_tc_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_mudur_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(fld_mudur_sifre_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btn_mudur_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        tabbed_p.addTab("Mudur Girisi", pnl_mudur_giris);

        jLabel3.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel3.setText("BANKA SISTEMINE HOSGELDINIZ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbed_p)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(177, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(162, 162, 162)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(tabbed_p))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(jLabel3)
                    .addContainerGap(270, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mudur_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mudur_girisActionPerformed
        if(fld_mudur_tc_giris.getText().length()==0 || new String(fld_mudur_sifre_giris.getPassword()).length()==0){
            JOptionPane.showMessageDialog(null,"Lutfen TC numaranizi ve Sifrenizi doldurunuz");
        }
        else{
            try {
                Connection con = conn.connDB();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT *"
                                                + "FROM mudur");
                boolean flag=false;
                
                while(rs.next()){
                    
                    if(fld_mudur_tc_giris.getText().equals(rs.getString("tc_no")) && new String(fld_mudur_sifre_giris.getPassword()).equals(rs.getString("sifre"))){
                        
                        Mudur mudur = new Mudur();
                        mudur.setTc(rs.getString("tc_no"));
                         mudur.setAd(rs.getString("ad"));
                          mudur.setSoyad(rs.getString("soyad"));
                           mudur.setSifre(rs.getString("sifre"));
                           
                        mudurGUI mGUI = new mudurGUI(mudur);
                        mGUI.setVisible(true);
                        dispose(); // giris jframe durdurma
                        flag=true;
                    }
                }
                
                // flag false kaldıysa kullanıcı yoktur demektir
                if(!flag)
                JOptionPane.showMessageDialog(null,"Girilen TC veya Sifreyle eslesen bir kullanici bulunamadi");
                
            } catch (Exception e) {
                
                e.printStackTrace();
            }
            
            
        }
    }//GEN-LAST:event_btn_mudur_girisActionPerformed

    private void btn_temsilci_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_temsilci_girisActionPerformed
        // TODO add your handling code here:
        if(fld_temsilci_tc_giris.getText().length()==0 || new String(fld_temsilci_sifre_giris1.getPassword()).length()==0){
            JOptionPane.showMessageDialog(null,"Lutfen TC numaranizi ve Sifrenizi doldurunuz");
        }
        else{
            try {
                Connection con = conn.connDB();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT *"
                                                + "FROM temsilci");
                boolean flag=false;
                
                while(rs.next()){
                    
                    if(fld_temsilci_tc_giris.getText().equals(rs.getString("tc_no")) && new String(fld_temsilci_sifre_giris1.getPassword()).equals(rs.getString("sifre"))){
                        
                        Temsilci temsilci = new Temsilci();
                        temsilci.setTc(rs.getString("tc_no"));
                         temsilci.setAd(rs.getString("ad"));
                          temsilci.setSoyad(rs.getString("soyad"));
                           temsilci.setSifre(rs.getString("sifre"));
                           
                        temsilciGUI tGUI = new temsilciGUI(temsilci);
                        tGUI.setVisible(true);
                        dispose(); // giris jframe durdurma
                        flag=true;
                    }
                }
                
                // flag false kaldıysa kullanıcı yoktur demektir
                if(!flag)
                JOptionPane.showMessageDialog(null,"Girilen TC veya Sifreyle eslesen bir kullanici bulunamadi");
                
            } catch (Exception e) {
                e.printStackTrace();
            }
            
            
        }
    }//GEN-LAST:event_btn_temsilci_girisActionPerformed

    private void btn_musteri_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_musteri_girisActionPerformed
        // TODO add your handling code here:
        
        if(fld_musteri_tc_giris.getText().length()==0 || new String(fld_musteri_sifre_giris.getPassword()).length()==0){
            JOptionPane.showMessageDialog(null,"Lutfen TC numaranizi ve Sifrenizi doldurunuz");
        }
        else{
            try {
                Connection con = conn.connDB();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT *"
                                                + "FROM musteri");
                boolean flag=false;
                
                while(rs.next()){
                    
                    if(fld_musteri_tc_giris.getText().equals(rs.getString("tc_no")) && new String(fld_musteri_sifre_giris.getPassword()).equals(rs.getString("sifre"))){
                        
                        Musteri musteri = new Musteri();
                        musteri.setTc(rs.getString("tc_no"));
                         musteri.setAd(rs.getString("ad"));
                          musteri.setSoyad(rs.getString("soyad"));
                           musteri.setSifre(rs.getString("sifre"));
                            musteri.setT_tc_no(rs.getString("t_tc_no"));
                           
                        musteriGUI mGUI = new musteriGUI(musteri);
                        mGUI.setVisible(true);
                        dispose(); // giris jframe durdurma
                        flag=true;
                    }
                }
                
                // flag false kaldıysa kullanıcı yoktur demektir
                if(!flag)
                JOptionPane.showMessageDialog(null,"Girilen TC veya Sifreyle eslesen bir kullanici bulunamadi");
                
            } catch (Exception e) {
                e.printStackTrace();
            }
            
            
        }
        
    }//GEN-LAST:event_btn_musteri_girisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(girisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(girisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(girisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(girisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new girisGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mudur_giris;
    private javax.swing.JButton btn_musteri_giris;
    private javax.swing.JButton btn_temsilci_giris;
    private javax.swing.JPasswordField fld_mudur_sifre_giris;
    private javax.swing.JTextField fld_mudur_tc_giris;
    private javax.swing.JPasswordField fld_musteri_sifre_giris;
    private javax.swing.JTextField fld_musteri_tc_giris;
    private javax.swing.JPasswordField fld_temsilci_sifre_giris1;
    private javax.swing.JTextField fld_temsilci_tc_giris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnl_mudur_giris;
    private javax.swing.JPanel pnl_musteri_giris;
    private javax.swing.JPanel pnl_temsilci_giris;
    private javax.swing.JTabbedPane tabbed_p;
    // End of variables declaration//GEN-END:variables
}
