/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arayuz;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tablolar.Durum;
import tablolar.Islem;
import tablolar.Kredi;
import tablolar.Mudur;
import tablolar.Musteri;
import tablolar.ParaBirimi;

/**
 *
 * @author 90543
 */
public class mudurGUI extends javax.swing.JFrame {

    /**
     * Creates new form mudurGUI
     */
    DefaultTableModel model = null; //table tanımlaması
    DefaultTableModel parabirimi_model = null; //para birimi table tanımlaması
    DefaultTableModel islem_model =null; // islem tablo tanımlaması
    DefaultTableModel islem_model22 =null;
    DefaultTableModel krediModel = null;
    static Mudur mudur = new Mudur();
    
    public mudurGUI(Mudur mudur) {
        this.mudur = mudur;
        initComponents();
        jLabel1.setText(mudur.getAd()+" "+mudur.getSoyad()+" giris yapti");
        tarihGoruntule();
        
        model = (DefaultTableModel)mudurun_musteri_tablosu.getModel(); //musteri tablosunu islem yapmak icin modele castingledik
        musteriGoruntule();
        
        parabirimi_model = (DefaultTableModel)mudur_parabirimi_tablosu.getModel(); //parabirim tablosundaki işlem yapmak icin csating
        parabirimiGoruntule();
        
        label_maas.setText(mudur.getMaas());
        
        faizGoruntule();
        
        durumGoruntule();
        
        islem_model = (DefaultTableModel)mudur_islem_tablo.getModel(); //islem tablosundaki işlem yapmak icin csating
        islemGoruntule();
        
        islem_model22 = (DefaultTableModel)mudur_islem22_tablo.getModel();
        islemGoruntule2();
        
        krediModel = (DefaultTableModel)mudur_kredi_table.getModel();
        krediGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_mudur_ekrani = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabbed_mudur = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fld_mudur_musteri_ekle_tc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fld_mudur_musteri_ekle_ad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fld_mudur_musteri_ekle_soyad = new javax.swing.JTextField();
        btn_mudur_musteri_ekle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mudurun_musteri_tablosu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mudur_parabirimi_tablosu = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fld_mudur_parabirimi_kurgiris = new javax.swing.JTextField();
        btn_mudur_parabirimi_ekle = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        fld_mudur_parabirimi_kurguncelle = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fld_mudur_parabirimi_adguncel = new javax.swing.JTextField();
        btn_mudur_parabirimi_guncelle = new javax.swing.JButton();
        fld_mudur_parabirimi_bad = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        label_maas = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fld_mudur_maas = new javax.swing.JTextField();
        btn_mudur_maas = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        label_faiz = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fld_mudur_faiz_guncelle = new javax.swing.JTextField();
        btn_mudur_faiz = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        fld_mudur_gfaiz_guncelle = new javax.swing.JTextField();
        btn_mudur_gfaiz = new javax.swing.JButton();
        label_gfaiz = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        label_mudur_gelir = new javax.swing.JLabel();
        label_mudur_gider = new javax.swing.JLabel();
        label_mudur_kaar = new javax.swing.JLabel();
        label_mudur_bakiye = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btn_mudur_ilerlet = new javax.swing.JButton();
        btn_mudur_genel_durum_guncelle = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mudur_islem_tablo = new javax.swing.JTable();
        combobox = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        btn_mudur_islem_getir = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        mudur_islem22_tablo = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        combobox22 = new javax.swing.JComboBox<>();
        btn_mudur_islem_getir22 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        mudur_kredi_table = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        btn_mudur_kredi_tablosu_guncelle = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btn_mudur_deadlock_analiz = new javax.swing.JButton();
        lbl_mudur_tarih = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mudur Ekrani");
        setLocation(new java.awt.Point(400, 200));
        setPreferredSize(new java.awt.Dimension(682, 386));
        setResizable(false);

        pnl_mudur_ekrani.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel1.setText("... giris yapti");

        tabbed_mudur.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel2.setText("Musteri Ekleme");

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel3.setText("Ad :");

        jLabel4.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel4.setText("TC No :");

        jLabel5.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel5.setText("Soyad :");

        fld_mudur_musteri_ekle_soyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_mudur_musteri_ekle_soyadActionPerformed(evt);
            }
        });

        btn_mudur_musteri_ekle.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        btn_mudur_musteri_ekle.setText("Ekle");
        btn_mudur_musteri_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mudur_musteri_ekleActionPerformed(evt);
            }
        });

        mudurun_musteri_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tc_no", "ad", "soyad", "sifre", "t_tc_no"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mudurun_musteri_tablosu);
        if (mudurun_musteri_tablosu.getColumnModel().getColumnCount() > 0) {
            mudurun_musteri_tablosu.getColumnModel().getColumn(0).setResizable(false);
            mudurun_musteri_tablosu.getColumnModel().getColumn(1).setResizable(false);
            mudurun_musteri_tablosu.getColumnModel().getColumn(2).setResizable(false);
            mudurun_musteri_tablosu.getColumnModel().getColumn(3).setResizable(false);
            mudurun_musteri_tablosu.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fld_mudur_musteri_ekle_ad, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(fld_mudur_musteri_ekle_tc)
                    .addComponent(fld_mudur_musteri_ekle_soyad)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btn_mudur_musteri_ekle)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fld_mudur_musteri_ekle_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fld_mudur_musteri_ekle_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fld_mudur_musteri_ekle_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_mudur_musteri_ekle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        tabbed_mudur.addTab("Musteri Ekleme", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        mudur_parabirimi_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "birim_ad", "kur"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mudur_parabirimi_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudur_parabirimi_tablosuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(mudur_parabirimi_tablosu);
        if (mudur_parabirimi_tablosu.getColumnModel().getColumnCount() > 0) {
            mudur_parabirimi_tablosu.getColumnModel().getColumn(0).setResizable(false);
            mudur_parabirimi_tablosu.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel6.setFont(new java.awt.Font("Sitka Subheading", 1, 14)); // NOI18N
        jLabel6.setText("Para Birimi Ekle");

        jLabel7.setFont(new java.awt.Font("Sitka Subheading", 1, 14)); // NOI18N
        jLabel7.setText("Kur Güncelle");

        jLabel8.setFont(new java.awt.Font("Sitka Subheading", 1, 14)); // NOI18N
        jLabel8.setText("Birim Adı :");

        jLabel9.setFont(new java.awt.Font("Sitka Subheading", 1, 14)); // NOI18N
        jLabel9.setText("Kur Degeri :");

        fld_mudur_parabirimi_kurgiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_mudur_parabirimi_kurgirisActionPerformed(evt);
            }
        });

        btn_mudur_parabirimi_ekle.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_mudur_parabirimi_ekle.setText("Ekle");
        btn_mudur_parabirimi_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mudur_parabirimi_ekleActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel10.setText("Kur Degeri : ");

        jLabel11.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel11.setText("Birim Adı :");

        fld_mudur_parabirimi_adguncel.setEditable(false);

        btn_mudur_parabirimi_guncelle.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_mudur_parabirimi_guncelle.setText("Guncelle");
        btn_mudur_parabirimi_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mudur_parabirimi_guncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fld_mudur_parabirimi_kurgiris, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fld_mudur_parabirimi_bad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fld_mudur_parabirimi_kurguncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fld_mudur_parabirimi_adguncel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btn_mudur_parabirimi_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_mudur_parabirimi_guncelle)
                .addGap(62, 62, 62))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(fld_mudur_parabirimi_adguncel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(fld_mudur_parabirimi_kurguncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(fld_mudur_parabirimi_bad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(fld_mudur_parabirimi_kurgiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btn_mudur_parabirimi_ekle))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btn_mudur_parabirimi_guncelle)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        tabbed_mudur.addTab("Para Birimi", jPanel2);

        jPanel3.setBackground(new java.awt.Color(102, 255, 102));

        jLabel12.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel12.setText("Temsilcilerin Guncel Maas Miktari ");

        label_maas.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        label_maas.setText("maas");

        jLabel14.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel14.setText("Temsilcilerin Maasini Guncelle");

        btn_mudur_maas.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_mudur_maas.setText("Guncelle");
        btn_mudur_maas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mudur_maasActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel13.setText("Faizlerin Guncel Miktarlari");

        label_faiz.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        label_faiz.setText("faiz");

        jLabel16.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel16.setText("Faiz Guncelle");

        btn_mudur_faiz.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_mudur_faiz.setText("Guncelle");
        btn_mudur_faiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mudur_faizActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel17.setText("GFaiz Guncelle");

        btn_mudur_gfaiz.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_mudur_gfaiz.setText("Guncelle");
        btn_mudur_gfaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mudur_gfaizActionPerformed(evt);
            }
        });

        label_gfaiz.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        label_gfaiz.setText("gfaiz");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(label_maas)
                    .addComponent(fld_mudur_maas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mudur_maas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_faiz)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fld_mudur_faiz_guncelle)
                                .addComponent(btn_mudur_faiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fld_mudur_gfaiz_guncelle)
                                    .addComponent(btn_mudur_gfaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(label_gfaiz)))
                        .addGap(65, 65, 65))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_maas)
                    .addComponent(label_faiz)
                    .addComponent(label_gfaiz))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fld_mudur_maas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_mudur_faiz_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_mudur_gfaiz_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mudur_maas)
                    .addComponent(btn_mudur_faiz)
                    .addComponent(btn_mudur_gfaiz))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        tabbed_mudur.addTab("Maas Ve Faiz", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 102, 255));

        jLabel15.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jLabel15.setText("Bankanın Genel Durum Ozeti");

        jLabel18.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel18.setText("Gider");

        jLabel19.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel19.setText("Gelir");

        jLabel20.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel20.setText("Toplam Bakiye");

        jLabel21.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel21.setText("Kaar");

        label_mudur_gelir.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        label_mudur_gelir.setText("ge");

        label_mudur_gider.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        label_mudur_gider.setText("ge");

        label_mudur_kaar.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        label_mudur_kaar.setText("ge");

        label_mudur_bakiye.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        label_mudur_bakiye.setText("ge");

        jLabel23.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jLabel23.setText("Sistemi 1 Ay Ilerlet");

        btn_mudur_ilerlet.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_mudur_ilerlet.setText("ilerlet");
        btn_mudur_ilerlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mudur_ilerletActionPerformed(evt);
            }
        });

        btn_mudur_genel_durum_guncelle.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_mudur_genel_durum_guncelle.setText("Guncelle");
        btn_mudur_genel_durum_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mudur_genel_durum_guncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(label_mudur_gelir))
                        .addGap(124, 124, 124)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_mudur_gider)
                            .addComponent(jLabel18))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(label_mudur_kaar)
                                .addGap(144, 144, 144)
                                .addComponent(label_mudur_bakiye))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(128, 128, 128)
                                .addComponent(jLabel20))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel15))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(btn_mudur_genel_durum_guncelle))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel23))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(btn_mudur_ilerlet)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_mudur_gelir)
                    .addComponent(label_mudur_gider)
                    .addComponent(label_mudur_kaar)
                    .addComponent(label_mudur_bakiye))
                .addGap(28, 28, 28)
                .addComponent(btn_mudur_genel_durum_guncelle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_mudur_ilerlet)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        tabbed_mudur.addTab("Genel Durum", jPanel4);

        jPanel5.setBackground(new java.awt.Color(51, 255, 204));

        mudur_islem_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ino", "kaynak", "hedef", "islem", "tutar", "kbakiye", "hbakiye", "tarih"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(mudur_islem_tablo);
        if (mudur_islem_tablo.getColumnModel().getColumnCount() > 0) {
            mudur_islem_tablo.getColumnModel().getColumn(0).setResizable(false);
            mudur_islem_tablo.getColumnModel().getColumn(1).setResizable(false);
            mudur_islem_tablo.getColumnModel().getColumn(2).setResizable(false);
            mudur_islem_tablo.getColumnModel().getColumn(3).setResizable(false);
            mudur_islem_tablo.getColumnModel().getColumn(4).setResizable(false);
            mudur_islem_tablo.getColumnModel().getColumn(5).setResizable(false);
            mudur_islem_tablo.getColumnModel().getColumn(6).setResizable(false);
            mudur_islem_tablo.getColumnModel().getColumn(7).setResizable(false);
        }

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hepsi", "2", "5", "10" }));

        jLabel22.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel22.setText("Islem Miktari : ");

        btn_mudur_islem_getir.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_mudur_islem_getir.setText("Getir");
        btn_mudur_islem_getir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mudur_islem_getirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel22)
                        .addGap(72, 72, 72)
                        .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(btn_mudur_islem_getir))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addComponent(btn_mudur_islem_getir)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        tabbed_mudur.addTab("Islemler", jPanel5);

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));

        mudur_islem22_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ino", "kaynak", "islem", "tutar", "kbakiye", "tarih"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(mudur_islem22_tablo);

        jLabel24.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel24.setText("Islem Miktari : ");

        combobox22.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hepsi", "2", "5", "10" }));

        btn_mudur_islem_getir22.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_mudur_islem_getir22.setText("Getir");
        btn_mudur_islem_getir22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mudur_islem_getir22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(72, 72, 72)
                        .addComponent(combobox22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btn_mudur_islem_getir22)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addComponent(btn_mudur_islem_getir22)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        tabbed_mudur.addTab("Islemler2", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 153, 153));

        mudur_kredi_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "miktar", "hno", "aylik", "afaiz", "agfaiz", "kalan_nborc", "odurum", "kalan_gun", "tarih", "mtc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mudur_kredi_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudur_kredi_tableMouseClicked(evt);
            }
        });
        jScrollPane14.setViewportView(mudur_kredi_table);

        jLabel25.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel25.setText("odurum = Odeme Durumu : 0-)Odenmedi  1-)Odendi  2-)Belirsiz ");

        btn_mudur_kredi_tablosu_guncelle.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_mudur_kredi_tablosu_guncelle.setText("Guncelle");
        btn_mudur_kredi_tablosu_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mudur_kredi_tablosu_guncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane14)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btn_mudur_kredi_tablosu_guncelle)))
                .addGap(94, 94, 94))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(btn_mudur_kredi_tablosu_guncelle)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        tabbed_mudur.addTab("Kredi", jPanel7);

        jPanel8.setBackground(new java.awt.Color(204, 0, 255));

        btn_mudur_deadlock_analiz.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_mudur_deadlock_analiz.setText("Analiz");
        btn_mudur_deadlock_analiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mudur_deadlock_analizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(btn_mudur_deadlock_analiz)
                .addGap(313, 313, 313))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(btn_mudur_deadlock_analiz)
                .addGap(123, 123, 123))
        );

        tabbed_mudur.addTab("DeadLock", jPanel8);

        lbl_mudur_tarih.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        lbl_mudur_tarih.setText("Tarih");

        javax.swing.GroupLayout pnl_mudur_ekraniLayout = new javax.swing.GroupLayout(pnl_mudur_ekrani);
        pnl_mudur_ekrani.setLayout(pnl_mudur_ekraniLayout);
        pnl_mudur_ekraniLayout.setHorizontalGroup(
            pnl_mudur_ekraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_mudur_ekraniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_mudur_tarih)
                .addGap(130, 130, 130))
            .addComponent(tabbed_mudur, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );
        pnl_mudur_ekraniLayout.setVerticalGroup(
            pnl_mudur_ekraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_mudur_ekraniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_mudur_ekraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_mudur_tarih))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabbed_mudur, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_mudur_ekrani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_mudur_ekrani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mudur_musteri_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mudur_musteri_ekleActionPerformed
        // TODO add your handling code here:
        if(fld_mudur_musteri_ekle_ad.getText().length()==0 || fld_mudur_musteri_ekle_soyad.getText().length()==0 || fld_mudur_musteri_ekle_tc.getText().length()==0){
            
            JOptionPane.showMessageDialog(null,"Lutfen boslukları eksiksiz doldurunuz");
        }
        else{
            
            String t_tc_no= mudur.getTemsilci();
            
           // System.out.println(fld_mudur_musteri_ekle_tc.getText());
            
            boolean flag = mudur.musteriEkle(fld_mudur_musteri_ekle_tc.getText(), fld_mudur_musteri_ekle_ad.getText(), fld_mudur_musteri_ekle_soyad.getText(),t_tc_no);
            
            if(flag){
                JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                
                musteriGoruntule(); //Tabloyu yenilemek icin
                
                fld_mudur_musteri_ekle_ad.setText(null);
                fld_mudur_musteri_ekle_soyad.setText(null); // degeleri 0 ladık güzel goruntu icin
                fld_mudur_musteri_ekle_tc.setText(null);
            }
            else{
                JOptionPane.showMessageDialog(null,"Bir hata ile karsilasildi");
                fld_mudur_musteri_ekle_ad.setText(null);
                fld_mudur_musteri_ekle_soyad.setText(null); // degeleri 0 ladık güzel goruntu icin
                fld_mudur_musteri_ekle_tc.setText(null);
            }
                
        }
    }//GEN-LAST:event_btn_mudur_musteri_ekleActionPerformed

    private void fld_mudur_parabirimi_kurgirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_mudur_parabirimi_kurgirisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_mudur_parabirimi_kurgirisActionPerformed

    private void btn_mudur_parabirimi_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mudur_parabirimi_ekleActionPerformed
        // TODO add your handling code here:
        
        if(fld_mudur_parabirimi_bad.getText().length()==0 || fld_mudur_parabirimi_kurgiris.getText().length()==0){
               JOptionPane.showMessageDialog(null,"Lutfen boslukları eksiksiz doldurunuz");
        }
        else{
            
            boolean flag = mudur.parabirimiEkle(fld_mudur_parabirimi_bad.getText(), Integer.parseInt(fld_mudur_parabirimi_kurgiris.getText()));
            
            if(flag){
                
                JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                
               parabirimiGoruntule(); //Tabloyu yenilemek icin
                
            }
            else{
                JOptionPane.showMessageDialog(null,"Bir hata ile karsilasildi");
            }
            
            fld_mudur_parabirimi_bad.setText(null);
            fld_mudur_parabirimi_kurgiris.setText(null);
            
            
        }
    }//GEN-LAST:event_btn_mudur_parabirimi_ekleActionPerformed

    private void mudur_parabirimi_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudur_parabirimi_tablosuMouseClicked
        // TODO add your handling code here:
        int seciliSatir = mudur_parabirimi_tablosu.getSelectedRow();
        // buradaki islemler secili satırdaki istenilen bilgileri istenilen yerlere ekler
        fld_mudur_parabirimi_adguncel.setText(parabirimi_model.getValueAt(seciliSatir, 1).toString());
        fld_mudur_parabirimi_kurguncelle.setText(parabirimi_model.getValueAt(seciliSatir, 2).toString());
    }//GEN-LAST:event_mudur_parabirimi_tablosuMouseClicked

    private void btn_mudur_parabirimi_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mudur_parabirimi_guncelleActionPerformed
        // TODO add your handling code here:
       
        
        int seciliSatir = mudur_parabirimi_tablosu.getSelectedRow();
        
        if(seciliSatir==-1){
            
            if(parabirimi_model.getRowCount()==0){  //tablonun bos olma durumu
            
                JOptionPane.showMessageDialog(null,"Tabloda veri bulunmamaktadir");
            }
            else{ 
                JOptionPane.showMessageDialog(null,"Lutfen guncellenicek veriyi seciniz"); //veri secilmemiş olması
            }
        }
        else{
            
            String bad = fld_mudur_parabirimi_adguncel.getText();
            int kur = Integer.parseInt(fld_mudur_parabirimi_kurguncelle.getText());
            int id = (int)parabirimi_model.getValueAt(seciliSatir,0);
            
            boolean flag = mudur.parabirimiGuncelle(id, kur);
            
            if(flag){
                
                JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                
                parabirimiGoruntule(); //Tabloyu yenilemek icin
            }
            else{
                
                JOptionPane.showMessageDialog(null,"Bir hata ile karsilasildi");
            }
            
            fld_mudur_parabirimi_adguncel.setText(null);
            fld_mudur_parabirimi_kurguncelle.setText(null);
            
        }
        
    }//GEN-LAST:event_btn_mudur_parabirimi_guncelleActionPerformed

    private void btn_mudur_maasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mudur_maasActionPerformed
        // TODO add your handling code here:
        if(fld_mudur_maas.getText().length()==0){
            
            JOptionPane.showMessageDialog(null,"Lutfen boslukları eksiksiz doldurunuz");  
        }
        else{
            
            int maas; // bu gidicek maas
            String maas2; //bu gelecek maas
             
            maas2=fld_mudur_maas.getText();
            maas=Integer.parseInt(maas2);   //ınt e casting ettik
            
            boolean flag = mudur.maasGuncelle(maas);
            
            if(flag){
                
                JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                label_maas.setText(mudur.getMaas());
            }
            else{
                
                JOptionPane.showMessageDialog(null,"Bir hata ile karsilasildi");
            }
            
            fld_mudur_maas.setText(null);
            
        }
    }//GEN-LAST:event_btn_mudur_maasActionPerformed

    private void btn_mudur_faizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mudur_faizActionPerformed
        // TODO add your handling code here:
        
        if(fld_mudur_faiz_guncelle.getText().length()==0){
            
            JOptionPane.showMessageDialog(null,"Lutfen boslukları eksiksiz doldurunuz");  
        }
        else{
            
            int faiz; // bu gidicek maas
            String faiz2; //bu gelecek maas
             
            faiz2=fld_mudur_faiz_guncelle.getText();
            faiz=Integer.parseInt(faiz2);   //ınt e casting ettik
            
            boolean flag = mudur.faizGuncelle(faiz);
            
             if(flag){
                
                JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                
                ArrayList<String> list = new ArrayList<String>();
                list=mudur.getFaiz();
                
                label_faiz.setText("Faiz : "+list.get(0));
                
            }
            else{
                
                JOptionPane.showMessageDialog(null,"Bir hata ile karsilasildi");
            }
            
            fld_mudur_faiz_guncelle.setText(null);
            
            
        }
    }//GEN-LAST:event_btn_mudur_faizActionPerformed

    private void btn_mudur_gfaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mudur_gfaizActionPerformed
        // TODO add your handling code here:
        
        if(fld_mudur_gfaiz_guncelle.getText().length()==0){
            
            JOptionPane.showMessageDialog(null,"Lutfen boslukları eksiksiz doldurunuz");  
        }
        else{
            
            int gfaiz; // bu gidicek maas
            String gfaiz2; //bu gelecek maas
             
            gfaiz2=fld_mudur_gfaiz_guncelle.getText();
            gfaiz=Integer.parseInt(gfaiz2);   //ınt e casting ettik
            
            boolean flag = mudur.gFaizGuncelle(gfaiz);
            
             if(flag){
                
                JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                
                ArrayList<String> list = new ArrayList<String>();
                list=mudur.getFaiz();
                
                label_gfaiz.setText("GFaiz : "+list.get(1));
                
            }
            else{
                
                JOptionPane.showMessageDialog(null,"Bir hata ile karsilasildi");
            }
            
            fld_mudur_gfaiz_guncelle.setText(null);
            
            
        }
    }//GEN-LAST:event_btn_mudur_gfaizActionPerformed

    private void btn_mudur_islem_getirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mudur_islem_getirActionPerformed
        
        String miktar = String.valueOf(combobox.getSelectedItem()); // objeyi string yaptık
        
        if(miktar.equals("Hepsi")){
            
            islemGoruntule();
             JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
            
            
        }
        else{
            
            islemMiktarGoruntule(miktar);
            JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
            
            
        }
    }//GEN-LAST:event_btn_mudur_islem_getirActionPerformed

    private void btn_mudur_ilerletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mudur_ilerletActionPerformed
        // TODO add your handling code here:
        
      
        
        
        boolean flag = mudur.tarihIlerlet();
        
        if(flag){
            
            tarihGoruntule();
        }
        
        boolean flag3 = mudur.krediBilgileriGuncelle();
        
        if(!flag3){
            
            System.out.println("kredi bilgisi guncelle hata");
        }
        
        boolean flag2 = mudur.krediDevamEttir();
        
        if(!flag2){
            
              System.out.println("Kredi listesi bostur");
        }
        
        
        
        
          // maasla odenecek
          
         boolean flag4 = mudur.temsilciMaasOde();
         if(!flag4){
             
             System.out.println("hata");
         }
          
          durumGoruntule();
          
          
          JOptionPane.showMessageDialog(null,"1 ay ilerletildi");
        
               
    }//GEN-LAST:event_btn_mudur_ilerletActionPerformed

    private void btn_mudur_islem_getir22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mudur_islem_getir22ActionPerformed
        // TODO add your handling code here:
        
        String miktar = String.valueOf(combobox22.getSelectedItem()); // objeyi string yaptık
        
        if(miktar.equals("Hepsi")){
            
            islemGoruntule2();
             JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
            
            
        }
        else{
            
            islemMiktarGoruntule2(miktar);
            JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
            
            
        }
    }//GEN-LAST:event_btn_mudur_islem_getir22ActionPerformed

    private void mudur_kredi_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudur_kredi_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mudur_kredi_tableMouseClicked

    private void btn_mudur_kredi_tablosu_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mudur_kredi_tablosu_guncelleActionPerformed
        // TODO add your handling code here:
        krediGoruntule();
        JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");

    }//GEN-LAST:event_btn_mudur_kredi_tablosu_guncelleActionPerformed

    private void fld_mudur_musteri_ekle_soyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_mudur_musteri_ekle_soyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_mudur_musteri_ekle_soyadActionPerformed

    private void btn_mudur_genel_durum_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mudur_genel_durum_guncelleActionPerformed
        // TODO add your handling code here:
        
        durumGoruntule();
        JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
    }//GEN-LAST:event_btn_mudur_genel_durum_guncelleActionPerformed

    private void btn_mudur_deadlock_analizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mudur_deadlock_analizActionPerformed
        // TODO add your handling code here:
        
        mudur.deadLockAnaliz();
        JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
    }//GEN-LAST:event_btn_mudur_deadlock_analizActionPerformed

    /**
     * @param args the command line arguments
     */
    public void musteriGoruntule(){
        
        model.setRowCount(0);
        
        ArrayList <Musteri> musteriler = new ArrayList <Musteri>();
        
        musteriler = mudur.getMusteriList(); // databasen gelen degerlerimizi aldık
        
        if(musteriler != null){
            
            for(Musteri musteri : musteriler){
                Object [] degerler ={musteri.getTc(),musteri.getAd(),musteri.getSoyad(),musteri.getSifre(),musteri.getT_tc_no()};
                
                model.addRow(degerler); //metodu object dizi aldıgından degerler dizisini object tanımladık
            }
        }
        
        
        
    }
    
    public void parabirimiGoruntule(){
        
        parabirimi_model.setRowCount(0);
        
        ArrayList <ParaBirimi> parabirimi = new ArrayList <ParaBirimi>();
        
        parabirimi = mudur.getParaBirimiList(); // databasen gelen degerlerimizi aldık
        
        if(parabirimi != null){
            
            for(ParaBirimi parabirimleri : parabirimi){
                Object [] degerler ={parabirimleri.getId(),parabirimleri.getBad(),parabirimleri.getKur()};
                
                parabirimi_model.addRow(degerler); //metodu object dizi aldıgından degerler dizisini object tanımladık
            }
        }
        
    }
    
    public void faizGoruntule(){  //belirlenen faiz arraylistini alıp gerekli label a degerleri aktarır
        ArrayList <String> list = new ArrayList<String>();
        
        list = mudur.getFaiz();
        if(list!=null){
        label_faiz.setText("Faiz : "+list.get(0));
        label_gfaiz.setText("GFaiz : "+list.get(1));
        }
        
    }
    
    public void durumGoruntule(){
        
        Durum durum = new Durum();
        
        durum=mudur.getDurum();
        
        if(durum!=null){
            
           label_mudur_gelir.setText(String.valueOf(durum.getGelir()));
           label_mudur_gider.setText(String.valueOf(durum.getGider()));
           label_mudur_kaar.setText(String.valueOf(durum.getKaar()));
           label_mudur_bakiye.setText(String.valueOf(durum.getToplamBakiye()));
        }
    }
    
    public void islemGoruntule(){
        
        islem_model.setRowCount(0);
        
        ArrayList <Islem> islemler = new ArrayList <Islem>();
        
        islemler = mudur.getIslemList(); // databasen gelen degerlerimizi aldık
        
        if(islemler != null){
            
            for(Islem islem : islemler){
                Object [] degerler ={islem.getIno(),islem.getKaynak(),islem.getHedef(),islem.getIslem(),islem.getTutar(),islem.getKbakiye(),islem.getHbakiye(),islem.getTarih()};
                
                islem_model.addRow(degerler); //metodu object dizi aldıgından degerler dizisini object tanımladık
            }
        }
        
    }
    
    public void islemMiktarGoruntule(String miktar){
        
         islem_model.setRowCount(0);
        
        ArrayList <Islem> islemler = new ArrayList <Islem>();
        
        islemler = mudur.getIslemMiktarList(miktar); // databasen gelen degerlerimizi aldık
        
        if(islemler != null){
            
            for(Islem islem : islemler){
                Object [] degerler ={islem.getIno(),islem.getKaynak(),islem.getHedef(),islem.getIslem(),islem.getTutar(),islem.getKbakiye(),islem.getHbakiye(),islem.getTarih()};
                
                islem_model.addRow(degerler); //metodu object dizi aldıgından degerler dizisini object tanımladık
            }
        }
        
        
    }
    
    
    public void islemGoruntule2(){
        
        islem_model22.setRowCount(0);
        
        ArrayList <Islem> islemler = new ArrayList <Islem>();
        
        islemler = mudur.getIslemList2(); // databasen gelen degerlerimizi aldık
        
        if(islemler != null){
            
            for(Islem islem : islemler){
                Object [] degerler ={islem.getIno(),islem.getKaynak(),islem.getIslem(),islem.getTutar(),islem.getKbakiye(),islem.getTarih()};
                
                islem_model22.addRow(degerler); //metodu object dizi aldıgından degerler dizisini object tanımladık
            }
        }
        
    }
    
    public void islemMiktarGoruntule2(String miktar){
        
         islem_model22.setRowCount(0);
        
        ArrayList <Islem> islemler = new ArrayList <Islem>();
        
        islemler = mudur.getIslemMiktarList2(miktar); // databasen gelen degerlerimizi aldık
        
        if(islemler != null){
            
            for(Islem islem : islemler){
                Object [] degerler ={islem.getIno(),islem.getKaynak(),islem.getIslem(),islem.getTutar(),islem.getKbakiye(),islem.getTarih()};
                
                islem_model22.addRow(degerler); //metodu object dizi aldıgından degerler dizisini object tanımladık
            }
        }
        
        
    }
    
    public void krediGoruntule(){
        
        krediModel.setRowCount(0);
        
        ArrayList <Kredi> krediler = new ArrayList <Kredi>();
        
        krediler = mudur.getOwnKrediList(); // databasen gelen degerlerimizi aldık
        
        if(krediler != null){
            
            for(Kredi kredi : krediler){
                Object [] degerler ={kredi.getMiktar(),kredi.getHno(),kredi.getAylik(),kredi.getAfaiz(),kredi.getAgfaiz(),kredi.getKalan_nborc(),kredi.getOdurum(),kredi.getKalan_gun(),kredi.getTarih(),kredi.getMtc()};
                
                krediModel.addRow(degerler); //metodu object dizi aldıgından degerler dizisini object tanımladık
            }
        }
        
    }
    
    public void tarihGoruntule(){
        
        String tarih = mudur.getNowDate();
        if(tarih!=null)
        lbl_mudur_tarih.setText(tarih);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mudurGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mudurGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mudurGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mudurGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mudurGUI(mudur).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mudur_deadlock_analiz;
    private javax.swing.JButton btn_mudur_faiz;
    private javax.swing.JButton btn_mudur_genel_durum_guncelle;
    private javax.swing.JButton btn_mudur_gfaiz;
    private javax.swing.JButton btn_mudur_ilerlet;
    private javax.swing.JButton btn_mudur_islem_getir;
    private javax.swing.JButton btn_mudur_islem_getir22;
    private javax.swing.JButton btn_mudur_kredi_tablosu_guncelle;
    private javax.swing.JButton btn_mudur_maas;
    private javax.swing.JButton btn_mudur_musteri_ekle;
    private javax.swing.JButton btn_mudur_parabirimi_ekle;
    private javax.swing.JButton btn_mudur_parabirimi_guncelle;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JComboBox<String> combobox22;
    private javax.swing.JTextField fld_mudur_faiz_guncelle;
    private javax.swing.JTextField fld_mudur_gfaiz_guncelle;
    private javax.swing.JTextField fld_mudur_maas;
    private javax.swing.JTextField fld_mudur_musteri_ekle_ad;
    private javax.swing.JTextField fld_mudur_musteri_ekle_soyad;
    private javax.swing.JTextField fld_mudur_musteri_ekle_tc;
    private javax.swing.JTextField fld_mudur_parabirimi_adguncel;
    private javax.swing.JTextField fld_mudur_parabirimi_bad;
    private javax.swing.JTextField fld_mudur_parabirimi_kurgiris;
    private javax.swing.JTextField fld_mudur_parabirimi_kurguncelle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_faiz;
    private javax.swing.JLabel label_gfaiz;
    private javax.swing.JLabel label_maas;
    private javax.swing.JLabel label_mudur_bakiye;
    private javax.swing.JLabel label_mudur_gelir;
    private javax.swing.JLabel label_mudur_gider;
    private javax.swing.JLabel label_mudur_kaar;
    private javax.swing.JLabel lbl_mudur_tarih;
    private javax.swing.JTable mudur_islem22_tablo;
    private javax.swing.JTable mudur_islem_tablo;
    private javax.swing.JTable mudur_kredi_table;
    private javax.swing.JTable mudur_parabirimi_tablosu;
    private javax.swing.JTable mudurun_musteri_tablosu;
    private javax.swing.JPanel pnl_mudur_ekrani;
    private javax.swing.JTabbedPane tabbed_mudur;
    // End of variables declaration//GEN-END:variables
}
