/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arayuz;

import ekPaket.DataBaseBaglanti;
import javax.swing.JOptionPane;
import tablolar.Temsilci;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import tablolar.Islem;
import tablolar.Kredi;
import tablolar.Madres;
import tablolar.Meposta;
import tablolar.Mtelefon;
import tablolar.Musteri;
import tablolar.Talep;

/**
 *
 * @author 90543
 */
public class temsilciGUI extends javax.swing.JFrame {

    /**
     * Creates new form temsilciGUI
     */
    
    static Temsilci temsilci = new Temsilci();
    private DataBaseBaglanti conn = new DataBaseBaglanti();  // istenilen degiskene temsilcinin izni var mı kontorl ic
                                                            //database baglantisiyle kontrol edicezgiz
    DefaultTableModel model = null; //Musteritable tanımlaması
   
    DefaultTableModel guncelleModelAdres = null;
    
    DefaultTableModel guncelleModelEposta = null;
    
    DefaultTableModel guncelleModelTelefon = null;
    
    DefaultTableModel islemModel = null;
    
    DefaultTableModel islemModel2 = null;
    
    DefaultTableModel talepModel = null;
    
    DefaultTableModel krediModel = null;
    
    
    
    public temsilciGUI(Temsilci temsilci) {
        this.temsilci = temsilci;
        initComponents();
        jLabel1.setText(temsilci.getAd()+" "+temsilci.getSoyad()+" Giris Yapti...");
        tarihGoruntule();
        
        model = (DefaultTableModel)temsilci_musteri_table.getModel(); // tablomuz icin modelimizi aldık
        musteriGoruntule();
        
        guncelleModelAdres = (DefaultTableModel)temsilci_guncelle_adres_table.getModel();
        adresGoruntule();
        
        guncelleModelEposta = (DefaultTableModel)temsilci_guncelle_eposta_table.getModel();
        epostaGoruntule();
        
        guncelleModelTelefon = (DefaultTableModel)temsilci_guncelle_telefon_table.getModel();
        telefonGoruntule();
        
        islemModel = (DefaultTableModel)temsilci_islem_tablo.getModel();
        islemGoruntule();
        
        islemModel2 = (DefaultTableModel)temsilci_islem22_tablo.getModel();
        islemGoruntule2();
        
        talepModel = (DefaultTableModel)temsilci_talep_table.getModel();
        talepGoruntule();
        
        krediModel = (DefaultTableModel)temsilci_kredi_table.getModel();
        krediGoruntule();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        temsilci_musteri_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fld_temsilci_tc_no_ekle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fld_temsilci_ad_ekle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fld_temsilci_soyad_ekle = new javax.swing.JTextField();
        btn_temsilci_muster_ekle = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fld_temsilci_tc_no_sil = new javax.swing.JTextField();
        btn_temsilci_musteri_sil = new javax.swing.JButton();
        btn_temsilci_duzenle = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        temsilci_guncelle_adres_table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        fld_temsilci_musteri_adres = new javax.swing.JTextField();
        fld_temsilci_musteri_adres_tc = new javax.swing.JTextField();
        fld_temsilci_musteri_adres_id = new javax.swing.JTextField();
        btn_tesilci_musteri_adres = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        temsilci_guncelle_eposta_table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        fld_temsilci_musteri_eposta_id = new javax.swing.JTextField();
        fld_temsilci_musteri_eposta = new javax.swing.JTextField();
        fld_temsilci_musteri_eposta_tc = new javax.swing.JTextField();
        btn_temsilci_musteri_eposta = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        temsilci_guncelle_telefon_table = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        fld_temsilci_musteri_telefon_id = new javax.swing.JTextField();
        fld_temsilci_musteri_telefon = new javax.swing.JTextField();
        fld_temsilci_musteri_telefon_tc = new javax.swing.JTextField();
        btn_temsilci_musteri_telefob = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        temsilci_islem_tablo = new javax.swing.JTable();
        combo_temsilci_islem = new javax.swing.JComboBox<>();
        btn_temsilci_islem = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        temsilci_talep_table = new javax.swing.JTable();
        temsilci_talep_yenile = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fld_temsilci_talep_id = new javax.swing.JTextField();
        fld_temsilci_talep_tc_no = new javax.swing.JTextField();
        fld_temsilci_talep_iad = new javax.swing.JTextField();
        fld_temsilci_talep_onay = new javax.swing.JTextField();
        btn_temsilci_talep_onay = new javax.swing.JButton();
        btn_tamsilci_talep_reddet = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        temsilci_kredi_table = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        btn_temsilci_kredi_tablosu_guncelle = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        temsilci_islem22_tablo = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        combo_temsilci_islem2 = new javax.swing.JComboBox<>();
        btn_temsilci_islem2 = new javax.swing.JButton();
        lbl_temsilci_tarih = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temsilci Ekrani");
        setLocation(new java.awt.Point(400, 200));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jLabel1.setText("... Giris Yapti");

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        temsilci_musteri_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tc_no", "ad", "soyad", "sifre", "t_tc_no"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        temsilci_musteri_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                temsilci_musteri_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(temsilci_musteri_table);
        if (temsilci_musteri_table.getColumnModel().getColumnCount() > 0) {
            temsilci_musteri_table.getColumnModel().getColumn(0).setResizable(false);
            temsilci_musteri_table.getColumnModel().getColumn(1).setResizable(false);
            temsilci_musteri_table.getColumnModel().getColumn(2).setResizable(false);
            temsilci_musteri_table.getColumnModel().getColumn(3).setResizable(false);
            temsilci_musteri_table.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel2.setText("Musteri Ekleme");

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel3.setText("TC No : ");

        jLabel4.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel4.setText("Ad : ");

        jLabel5.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel5.setText("Soyad : ");

        btn_temsilci_muster_ekle.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_temsilci_muster_ekle.setText("Ekle");
        btn_temsilci_muster_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_temsilci_muster_ekleActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel6.setText("Musteri Silme");

        jLabel7.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel7.setText("TC No : ");

        btn_temsilci_musteri_sil.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_temsilci_musteri_sil.setText("Sil");
        btn_temsilci_musteri_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_temsilci_musteri_silActionPerformed(evt);
            }
        });

        btn_temsilci_duzenle.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_temsilci_duzenle.setText("Duzenle");
        btn_temsilci_duzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_temsilci_duzenleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(1, 1, 1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(fld_temsilci_tc_no_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                            .addComponent(fld_temsilci_ad_ekle)
                                            .addComponent(fld_temsilci_soyad_ekle)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fld_temsilci_tc_no_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_temsilci_muster_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_temsilci_duzenle)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_temsilci_musteri_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fld_temsilci_tc_no_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(fld_temsilci_ad_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(fld_temsilci_soyad_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_temsilci_muster_ekle)
                            .addComponent(btn_temsilci_duzenle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(fld_temsilci_tc_no_sil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_temsilci_musteri_sil)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Ekle Sil Guncelle", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));

        temsilci_guncelle_adres_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "adres", "tc_no"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        temsilci_guncelle_adres_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                temsilci_guncelle_adres_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(temsilci_guncelle_adres_table);
        if (temsilci_guncelle_adres_table.getColumnModel().getColumnCount() > 0) {
            temsilci_guncelle_adres_table.getColumnModel().getColumn(0).setResizable(false);
            temsilci_guncelle_adres_table.getColumnModel().getColumn(1).setResizable(false);
            temsilci_guncelle_adres_table.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel8.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel8.setText("Adres");

        fld_temsilci_musteri_adres_tc.setEditable(false);

        fld_temsilci_musteri_adres_id.setEditable(false);

        btn_tesilci_musteri_adres.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_tesilci_musteri_adres.setText("Guncelle");
        btn_tesilci_musteri_adres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tesilci_musteri_adresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel8)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fld_temsilci_musteri_adres_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fld_temsilci_musteri_adres, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_tesilci_musteri_adres)
                                .addGap(80, 80, 80))))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(474, Short.MAX_VALUE)
                    .addComponent(fld_temsilci_musteri_adres_id, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(62, 62, 62)
                .addComponent(fld_temsilci_musteri_adres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(fld_temsilci_musteri_adres_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_tesilci_musteri_adres)
                .addGap(89, 89, 89))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(fld_temsilci_musteri_adres_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(207, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Adres", jPanel3);

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));

        temsilci_guncelle_eposta_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "eposta", "tc_no"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        temsilci_guncelle_eposta_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                temsilci_guncelle_eposta_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(temsilci_guncelle_eposta_table);
        if (temsilci_guncelle_eposta_table.getColumnModel().getColumnCount() > 0) {
            temsilci_guncelle_eposta_table.getColumnModel().getColumn(0).setResizable(false);
            temsilci_guncelle_eposta_table.getColumnModel().getColumn(1).setResizable(false);
            temsilci_guncelle_eposta_table.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel9.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel9.setText("Eposta");

        fld_temsilci_musteri_eposta_id.setEditable(false);

        fld_temsilci_musteri_eposta_tc.setEditable(false);

        btn_temsilci_musteri_eposta.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_temsilci_musteri_eposta.setText("Guncelle");
        btn_temsilci_musteri_eposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_temsilci_musteri_epostaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(89, 89, 89))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(fld_temsilci_musteri_eposta_id, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fld_temsilci_musteri_eposta_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fld_temsilci_musteri_eposta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_temsilci_musteri_eposta)
                        .addGap(75, 75, 75))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(fld_temsilci_musteri_eposta_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fld_temsilci_musteri_eposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fld_temsilci_musteri_eposta_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_temsilci_musteri_eposta))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eposta", jPanel4);

        jPanel5.setBackground(new java.awt.Color(102, 255, 102));

        temsilci_guncelle_telefon_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "tel_no", "tc_no"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        temsilci_guncelle_telefon_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                temsilci_guncelle_telefon_tableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(temsilci_guncelle_telefon_table);
        if (temsilci_guncelle_telefon_table.getColumnModel().getColumnCount() > 0) {
            temsilci_guncelle_telefon_table.getColumnModel().getColumn(0).setResizable(false);
            temsilci_guncelle_telefon_table.getColumnModel().getColumn(1).setResizable(false);
            temsilci_guncelle_telefon_table.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel10.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel10.setText("Telefon");

        fld_temsilci_musteri_telefon_id.setEditable(false);

        fld_temsilci_musteri_telefon_tc.setEditable(false);

        btn_temsilci_musteri_telefob.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_temsilci_musteri_telefob.setText("Guncelle");
        btn_temsilci_musteri_telefob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_temsilci_musteri_telefobActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(93, 93, 93))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(fld_temsilci_musteri_telefon_id, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fld_temsilci_musteri_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fld_temsilci_musteri_telefon_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_temsilci_musteri_telefob)
                        .addGap(72, 72, 72))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fld_temsilci_musteri_telefon_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(fld_temsilci_musteri_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(fld_temsilci_musteri_telefon_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_temsilci_musteri_telefob))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Telefon", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));

        temsilci_islem_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ino", "kaynak", "hedef", "islem", "tutar", "kbakiye", "hbakiye", "tarih"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(temsilci_islem_tablo);

        combo_temsilci_islem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hepsi", "2", "5", "10" }));

        btn_temsilci_islem.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_temsilci_islem.setText("Getir");
        btn_temsilci_islem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_temsilci_islemActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel11.setText("Islem Miktari : ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(78, 78, 78)
                                .addComponent(combo_temsilci_islem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(224, 224, 224))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(btn_temsilci_islem, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(285, 285, 285))))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_temsilci_islem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(btn_temsilci_islem)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Islem", jPanel6);

        jPanel7.setBackground(new java.awt.Color(153, 255, 204));

        temsilci_talep_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "tc_no", "iad", "onay"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        temsilci_talep_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                temsilci_talep_tableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(temsilci_talep_table);
        if (temsilci_talep_table.getColumnModel().getColumnCount() > 0) {
            temsilci_talep_table.getColumnModel().getColumn(0).setResizable(false);
            temsilci_talep_table.getColumnModel().getColumn(1).setResizable(false);
            temsilci_talep_table.getColumnModel().getColumn(2).setResizable(false);
            temsilci_talep_table.getColumnModel().getColumn(3).setResizable(false);
        }

        temsilci_talep_yenile.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        temsilci_talep_yenile.setText("Yenile");
        temsilci_talep_yenile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temsilci_talep_yenileActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel12.setText("1-)Onayla");

        jLabel13.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel13.setText("0-)Reddet");

        jLabel14.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel14.setText("2-)Belirsiz");

        fld_temsilci_talep_id.setEditable(false);

        fld_temsilci_talep_tc_no.setEditable(false);

        fld_temsilci_talep_iad.setEditable(false);

        fld_temsilci_talep_onay.setEditable(false);

        btn_temsilci_talep_onay.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_temsilci_talep_onay.setText("Onay");
        btn_temsilci_talep_onay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_temsilci_talep_onayActionPerformed(evt);
            }
        });

        btn_tamsilci_talep_reddet.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_tamsilci_talep_reddet.setText("Reddet");
        btn_tamsilci_talep_reddet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tamsilci_talep_reddetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(temsilci_talep_yenile))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(jLabel12)
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel14))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fld_temsilci_talep_tc_no, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fld_temsilci_talep_id, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fld_temsilci_talep_iad, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fld_temsilci_talep_onay, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(24, 24, 24)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(btn_temsilci_talep_onay, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_tamsilci_talep_reddet)
                                .addGap(13, 13, 13)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addComponent(fld_temsilci_talep_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_temsilci_talep_tc_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_temsilci_talep_iad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_temsilci_talep_onay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_temsilci_talep_onay)
                            .addComponent(btn_tamsilci_talep_reddet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(temsilci_talep_yenile)
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Talepler", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 153, 153));

        temsilci_kredi_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "miktar", "hno", "aylik", "afaiz", "agfaiz", "kalan_nborc", "odurum", "kalan_gun", "tarih", "mtc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        temsilci_kredi_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                temsilci_kredi_tableMouseClicked(evt);
            }
        });
        jScrollPane14.setViewportView(temsilci_kredi_table);
        if (temsilci_kredi_table.getColumnModel().getColumnCount() > 0) {
            temsilci_kredi_table.getColumnModel().getColumn(0).setResizable(false);
            temsilci_kredi_table.getColumnModel().getColumn(0).setPreferredWidth(50);
            temsilci_kredi_table.getColumnModel().getColumn(1).setResizable(false);
            temsilci_kredi_table.getColumnModel().getColumn(1).setPreferredWidth(50);
            temsilci_kredi_table.getColumnModel().getColumn(2).setResizable(false);
            temsilci_kredi_table.getColumnModel().getColumn(2).setPreferredWidth(50);
            temsilci_kredi_table.getColumnModel().getColumn(3).setResizable(false);
            temsilci_kredi_table.getColumnModel().getColumn(3).setPreferredWidth(50);
            temsilci_kredi_table.getColumnModel().getColumn(4).setResizable(false);
            temsilci_kredi_table.getColumnModel().getColumn(4).setPreferredWidth(50);
            temsilci_kredi_table.getColumnModel().getColumn(5).setResizable(false);
            temsilci_kredi_table.getColumnModel().getColumn(5).setPreferredWidth(80);
            temsilci_kredi_table.getColumnModel().getColumn(6).setResizable(false);
            temsilci_kredi_table.getColumnModel().getColumn(6).setPreferredWidth(50);
            temsilci_kredi_table.getColumnModel().getColumn(7).setResizable(false);
            temsilci_kredi_table.getColumnModel().getColumn(7).setPreferredWidth(60);
            temsilci_kredi_table.getColumnModel().getColumn(8).setResizable(false);
            temsilci_kredi_table.getColumnModel().getColumn(8).setPreferredWidth(80);
            temsilci_kredi_table.getColumnModel().getColumn(9).setResizable(false);
            temsilci_kredi_table.getColumnModel().getColumn(9).setPreferredWidth(100);
        }

        jLabel17.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel17.setText("odurum = Odeme Durumu : 0-)Odenmedi  1-)Odendi  2-)Belirsiz ");

        btn_temsilci_kredi_tablosu_guncelle.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_temsilci_kredi_tablosu_guncelle.setText("Guncelle");
        btn_temsilci_kredi_tablosu_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_temsilci_kredi_tablosu_guncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel17))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(btn_temsilci_kredi_tablosu_guncelle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(btn_temsilci_kredi_tablosu_guncelle)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kredi", jPanel8);

        jPanel9.setBackground(new java.awt.Color(102, 255, 204));

        temsilci_islem22_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ino", "kaynak", "islem", "tutar", "kbakiye", "tarih"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(temsilci_islem22_tablo);

        jLabel15.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel15.setText("Islem Miktari : ");

        combo_temsilci_islem2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hepsi", "2", "5", "10" }));

        btn_temsilci_islem2.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btn_temsilci_islem2.setText("Getir");
        btn_temsilci_islem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_temsilci_islem2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                .addGap(11, 11, 11))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(78, 78, 78)
                        .addComponent(combo_temsilci_islem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(btn_temsilci_islem2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_temsilci_islem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(btn_temsilci_islem2)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Islem2", jPanel9);

        lbl_temsilci_tarih.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        lbl_temsilci_tarih.setText("Tarih");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_temsilci_tarih)
                .addGap(59, 59, 59))
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_temsilci_tarih))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_temsilci_muster_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_temsilci_muster_ekleActionPerformed
        // TODO add your handling code here:
        if(fld_temsilci_ad_ekle.getText().length()==0 || fld_temsilci_soyad_ekle.getText().length()==0 || fld_temsilci_soyad_ekle.getText().length()==0){
            
            JOptionPane.showMessageDialog(null,"Lutfen boslukları eksiksiz doldurunuz");
        }
        else{
            
            boolean flag = temsilci.musteriEkle(fld_temsilci_tc_no_ekle.getText(), fld_temsilci_ad_ekle.getText(), fld_temsilci_soyad_ekle.getText());
            
            if(flag){
                
                JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                
                musteriGoruntule();
            }
            else{
                JOptionPane.showMessageDialog(null,"Bir hata ile karsilasildi");
            }
            
            fld_temsilci_ad_ekle.setText(null);
            fld_temsilci_soyad_ekle.setText(null);
            fld_temsilci_tc_no_ekle.setText(null);
            
        }
    }//GEN-LAST:event_btn_temsilci_muster_ekleActionPerformed

    private void btn_temsilci_musteri_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_temsilci_musteri_silActionPerformed
        // TODO add your handling code here:
        
        boolean izin = false;
        
        if(fld_temsilci_tc_no_sil.getText().length()==0){
            
            JOptionPane.showMessageDialog(null,"Lutfen boslukları eksiksiz doldurunuz");
        }
        else{
            
            try {
                
                Connection con = conn.connDB();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT *"
                                                + "FROM musteri");
                
                
                while(rs.next()){
                    
                    if(rs.getString("t_tc_no").equals(temsilci.getTc())){
                        
                        izin = true;    // burdaki kontrol 
                    }
                    
                }
                
            } catch (Exception e) {
                e.printStackTrace();
                System.out.println("temsilciMusteriSilbtn da izin hatası");
                
            }
            
            try {
                
                if(izin){
                    
                    boolean flag = temsilci.musteriSil(fld_temsilci_tc_no_sil.getText());
                    
                    if(flag){
                        
                        JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                        musteriGoruntule();
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Bir hata ile karsilasildi");
                    }
                    
                    fld_temsilci_tc_no_sil.setText(null);
                }
                else{
                    
                    JOptionPane.showMessageDialog(null,"Secili musteriyi silme izniniz yoktur");
                }
                
            } catch (Exception e) {
                e.printStackTrace();
                System.out.println("temsilciMusteriSil hata");
            }
            
        }
    }//GEN-LAST:event_btn_temsilci_musteri_silActionPerformed

    private void temsilci_musteri_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temsilci_musteri_tableMouseClicked
        // TODO add your handling code here:
        int seciliSatir = temsilci_musteri_table.getSelectedRow();
        
        fld_temsilci_tc_no_sil.setText(model.getValueAt(seciliSatir,0).toString());
        fld_temsilci_tc_no_ekle.setText(model.getValueAt(seciliSatir,0).toString());
        fld_temsilci_ad_ekle.setText(model.getValueAt(seciliSatir,1).toString());
        fld_temsilci_soyad_ekle.setText(model.getValueAt(seciliSatir,2).toString());
    }//GEN-LAST:event_temsilci_musteri_tableMouseClicked

    private void btn_temsilci_duzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_temsilci_duzenleActionPerformed
        // TODO add your handling code here:
        boolean izin = false;
        
        if(fld_temsilci_tc_no_ekle.getText().length()==0 || fld_temsilci_ad_ekle.getText().length()==0 || fld_temsilci_soyad_ekle.getText().length()==0){
            
            JOptionPane.showMessageDialog(null,"Lutfen boslukları eksiksiz doldurunuz");
        }
        else{
            
            try {
                
                Connection con = conn.connDB();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT *"
                                                + "FROM musteri");
                
                
                while(rs.next()){
                    
                    if(rs.getString("t_tc_no").equals(temsilci.getTc())){
                        
                        izin = true;    // burdaki kontrol 
                    }
                    
                }
                
            } catch (Exception e) {
                e.printStackTrace();
                System.out.println("temsilciMusteriGuncellebtn da izin hatası");
                
            }
            
            try {
                
                if(izin){
                    
                    //System.out.println(fld_temsilci_tc_no_ekle.getText());
                    
                    boolean flag = temsilci.musteriGuncelle(fld_temsilci_tc_no_ekle.getText(), fld_temsilci_ad_ekle.getText(), fld_temsilci_soyad_ekle.getText());
                    
                    if(flag){
                        
                        JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                        musteriGoruntule();
                        
                    }
                    else{
                        
                        JOptionPane.showMessageDialog(null,"Bir hata ile karsilasildi");
                        
                    }
                    
                    fld_temsilci_ad_ekle.setText(null);
                    fld_temsilci_soyad_ekle.setText(null);
                    fld_temsilci_tc_no_ekle.setText(null);
                }
                else{
                    
                    JOptionPane.showMessageDialog(null,"Secili musteriyi silme izniniz yoktur");
                    
                }
                
            } catch (Exception e) {
                e.printStackTrace();
                System.out.println("temsilciMusteriGuncelle hata");
            }
        }    
        
        
    }//GEN-LAST:event_btn_temsilci_duzenleActionPerformed

    private void temsilci_guncelle_adres_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temsilci_guncelle_adres_tableMouseClicked
        // TODO add your handling code here:
        
        int seciliSatir = temsilci_guncelle_adres_table.getSelectedRow();
        fld_temsilci_musteri_adres_id.setText(guncelleModelAdres.getValueAt(seciliSatir,0).toString());
        fld_temsilci_musteri_adres.setText(guncelleModelAdres.getValueAt(seciliSatir,1).toString());
        fld_temsilci_musteri_adres_tc.setText(guncelleModelAdres.getValueAt(seciliSatir,2).toString());
        
    }//GEN-LAST:event_temsilci_guncelle_adres_tableMouseClicked

    private void temsilci_guncelle_eposta_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temsilci_guncelle_eposta_tableMouseClicked
        // TODO add your handling code here:
        
        int seciliSatir = temsilci_guncelle_eposta_table.getSelectedRow();
        
        fld_temsilci_musteri_eposta_id.setText(guncelleModelEposta.getValueAt(seciliSatir, 0).toString());
        fld_temsilci_musteri_eposta.setText(guncelleModelEposta.getValueAt(seciliSatir, 1).toString());
        fld_temsilci_musteri_eposta_tc.setText(guncelleModelEposta.getValueAt(seciliSatir, 2).toString());
    }//GEN-LAST:event_temsilci_guncelle_eposta_tableMouseClicked

    private void btn_temsilci_musteri_epostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_temsilci_musteri_epostaActionPerformed
        // TODO add your handling code here:
        if(fld_temsilci_musteri_eposta.getText().length() == 0){
            
            JOptionPane.showMessageDialog(null,"Lutfen boslukları eksiksiz doldurunuz");
            
        }
        else{
            
            int id = Integer.parseInt(fld_temsilci_musteri_eposta_id.getText());
            
            boolean flag =temsilci.musteriGuncelleEposta(fld_temsilci_musteri_eposta_tc.getText(), fld_temsilci_musteri_eposta.getText(), id);
            
            if(flag){
                
                JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                epostaGoruntule();
                
            }
            else{
                
                JOptionPane.showMessageDialog(null,"Bir hata ile karsilasildi");
            }
            
            fld_temsilci_musteri_eposta_id.setText(null);
            fld_temsilci_musteri_eposta.setText(null);
            fld_temsilci_musteri_eposta_tc.setText(null);
            
           
        }
    }//GEN-LAST:event_btn_temsilci_musteri_epostaActionPerformed

    private void temsilci_guncelle_telefon_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temsilci_guncelle_telefon_tableMouseClicked
        // TODO add your handling code here:
        
        int seciliSatir = temsilci_guncelle_telefon_table.getSelectedRow();
        fld_temsilci_musteri_telefon_id.setText(guncelleModelTelefon.getValueAt(seciliSatir,0).toString());
        fld_temsilci_musteri_telefon.setText(guncelleModelTelefon.getValueAt(seciliSatir,1).toString());
        fld_temsilci_musteri_telefon_tc.setText(guncelleModelTelefon.getValueAt(seciliSatir,2).toString());
    }//GEN-LAST:event_temsilci_guncelle_telefon_tableMouseClicked

    private void btn_tesilci_musteri_adresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tesilci_musteri_adresActionPerformed
        // TODO add your handling code here:
        
        if(fld_temsilci_musteri_adres.getText().length() == 0){
            
            JOptionPane.showMessageDialog(null,"Lutfen boslukları eksiksiz doldurunuz");
            
        }
        else{
            
            int id = Integer.parseInt(fld_temsilci_musteri_adres_id.getText());
            
            boolean flag =temsilci.musteriGuncelleAdres(fld_temsilci_musteri_adres_tc.getText(), fld_temsilci_musteri_adres.getText(), id);
            
            if(flag){
                
                JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                adresGoruntule();
                
            }
            else{
                
                JOptionPane.showMessageDialog(null,"Bir hata ile karsilasildi");
            }
            
            fld_temsilci_musteri_adres.setText(null);
            fld_temsilci_musteri_adres_id.setText(null);
            fld_temsilci_musteri_adres_tc.setText(null);
            
           
        }

    }//GEN-LAST:event_btn_tesilci_musteri_adresActionPerformed

    private void btn_temsilci_musteri_telefobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_temsilci_musteri_telefobActionPerformed
        // TODO add your handling code here:
        
        if(fld_temsilci_musteri_telefon.getText().length() == 0){
            
            JOptionPane.showMessageDialog(null,"Lutfen boslukları eksiksiz doldurunuz");
            
        }
        else{
            
            int id = Integer.parseInt(fld_temsilci_musteri_telefon_id.getText());
            
            boolean flag =temsilci.musteriGuncelleTelefon(fld_temsilci_musteri_telefon_tc.getText(), fld_temsilci_musteri_telefon.getText(), id);
            
            if(flag){
                
                JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                telefonGoruntule();
                
            }
            else{
                
                JOptionPane.showMessageDialog(null,"Bir hata ile karsilasildi");
            }
            
            fld_temsilci_musteri_telefon.setText(null);
            fld_temsilci_musteri_telefon_id.setText(null);
            fld_temsilci_musteri_telefon_tc.setText(null);
            
           
        }

    }//GEN-LAST:event_btn_temsilci_musteri_telefobActionPerformed

    private void btn_temsilci_islemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_temsilci_islemActionPerformed
        // TODO add your handling code here:
        
        String miktar = String.valueOf(combo_temsilci_islem.getSelectedItem()); // objeyi string yaptık
        
        if(miktar.equals("Hepsi")){
            
            islemGoruntule();
             JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
            
            
        }
        else{
            
            islemMiktarGoruntule(miktar);
            JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
            
            
        }
        
    }//GEN-LAST:event_btn_temsilci_islemActionPerformed

    private void temsilci_talep_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temsilci_talep_tableMouseClicked
        // TODO add your handling code here:
        
        int seciliSatir = temsilci_talep_table.getSelectedRow();
        fld_temsilci_talep_id.setText(talepModel.getValueAt(seciliSatir,0).toString());
        fld_temsilci_talep_tc_no.setText(talepModel.getValueAt(seciliSatir,1).toString());
        fld_temsilci_talep_iad.setText(talepModel.getValueAt(seciliSatir,2).toString());
        fld_temsilci_talep_onay.setText(talepModel.getValueAt(seciliSatir, 3).toString());
    }//GEN-LAST:event_temsilci_talep_tableMouseClicked

    private void temsilci_talep_yenileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temsilci_talep_yenileActionPerformed
        // TODO add your handling code here:
        talepGoruntule();
        JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
        
    }//GEN-LAST:event_temsilci_talep_yenileActionPerformed

    private void btn_temsilci_talep_onayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_temsilci_talep_onayActionPerformed
        // TODO add your handling code here:
        if(fld_temsilci_talep_id.getText().length()==0){
            
            JOptionPane.showMessageDialog(null,"Lutfen boslukları eksiksiz doldurunuz");
            
        }
        else{
            
            int id = Integer.parseInt(fld_temsilci_talep_id.getText());
           
            
            boolean flag = temsilci.setTalep(id,1);
            
            if(flag){
                
                System.out.println(" girdim");
                
                boolean flag2 = false;
                
                    if(fld_temsilci_talep_iad.getText().equals("hesap acma")){  //hesap acma islemi ise
                     
                       flag2 = temsilci.hAcmaTalepOnay(id);
                        if(flag2){
                    
                            boolean flag3 = temsilci.hesapAcmaTalepSil(id);
                    
                           if(flag3){
                        
                                JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                                talepGoruntule();
                        
                            }
                     
                        }
             
                    }
                    else if(fld_temsilci_talep_iad.getText().equals("kredi")){ //kredi islemi
                        
                    
                        flag2 = temsilci.krediTalepOnay(id , lbl_temsilci_tarih.getText());
                        if(flag2){
                            
                            boolean flag3 = temsilci.krediTalepSil(id);
                            if(flag3){
                                
                                JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                                talepGoruntule();
                                
                            }
                        }
                    }
                    else if(fld_temsilci_talep_iad.getText().equals("hesap silme")){ //hesap silme islemi
                        
                        System.out.println("girdimmm");
                        flag2 = temsilci.hesapSilmeTalepOnay(id);
                        if(flag2){
                            
                            System.out.println("girdim");
                            
                            boolean flag3 = temsilci.hesapSilmeTalepSilme(id);
                            if(flag3){
                                
                                JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                                talepGoruntule();
                                
                            }
                        }
                        
                        
                        
                    }
                
                   
            }
            else{
                
                JOptionPane.showMessageDialog(null,"Bir hata ile karsilasildi");
            }
            
            fld_temsilci_talep_iad.setText(null);
            fld_temsilci_talep_id.setText(null);
            fld_temsilci_talep_onay.setText(null);
            fld_temsilci_talep_tc_no.setText(null);
        }
    }//GEN-LAST:event_btn_temsilci_talep_onayActionPerformed

    private void btn_tamsilci_talep_reddetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tamsilci_talep_reddetActionPerformed
        // TODO add your handling code here:
        
        if(fld_temsilci_talep_id.getText().length()==0){
            
            JOptionPane.showMessageDialog(null,"Lutfen boslukları eksiksiz doldurunuz");
            
        }
        else{
            
            int id = Integer.parseInt(fld_temsilci_talep_id.getText());
           
            
            boolean flag = temsilci.setTalep(id,0);
            
            if(flag){
                
                boolean flag2 = false;
                
                if(fld_temsilci_talep_iad.getText().equals("hesap acma")){
                    
                    flag2 = temsilci.hesapAcmaTalepSil(id);
                    
                    if(flag2){
                        
                        JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                                talepGoruntule();
                    }
                }
                
                else if(fld_temsilci_talep_iad.getText().equals("kredi")){
                    
                    flag2 = temsilci.krediTalepSil(id);
                    
                    if(flag2){
                        
                        JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                                talepGoruntule();
                    }
                    
                }
                
                else if(fld_temsilci_talep_iad.getText().equals("hesap silme")){
                    
                    flag2 = temsilci.hesapSilmeTalepSilme2(id);
                    
                    if(flag2){
                        
                        JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
                                talepGoruntule();
                        
                    }
                    
                    
                }
                   
            }
            else{
                
                JOptionPane.showMessageDialog(null,"Bir hata ile karsilasildi");
            }
            
            fld_temsilci_talep_iad.setText(null);
            fld_temsilci_talep_id.setText(null);
            fld_temsilci_talep_onay.setText(null);
            fld_temsilci_talep_tc_no.setText(null);
        }
    }//GEN-LAST:event_btn_tamsilci_talep_reddetActionPerformed

    private void temsilci_kredi_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temsilci_kredi_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_temsilci_kredi_tableMouseClicked

    private void btn_temsilci_kredi_tablosu_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_temsilci_kredi_tablosu_guncelleActionPerformed
        // TODO add your handling code here:
        krediGoruntule();
        JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
        
    }//GEN-LAST:event_btn_temsilci_kredi_tablosu_guncelleActionPerformed

    private void btn_temsilci_islem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_temsilci_islem2ActionPerformed
        // TODO add your handling code here:
        
        String miktar = String.valueOf(combo_temsilci_islem2.getSelectedItem()); // objeyi string yaptık
        
        if(miktar.equals("Hepsi")){
            
            islemGoruntule2();
             JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
            
            
        }
        else{
            
            islemMiktarGoruntule2(miktar);
            JOptionPane.showMessageDialog(null,"Islem basarili bir sekilde gerceklesti");
            
            
        }
    }//GEN-LAST:event_btn_temsilci_islem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void musteriGoruntule(){
        
        model.setRowCount(0);
        
        ArrayList <Musteri> musteriler = new ArrayList <Musteri>();
        
        musteriler = temsilci.getOwnMusteriList(); // databaseeden gelen musterileri aldık
        
        if(musteriler != null){
            
            for(Musteri musteri : musteriler){
                Object [] degerler ={musteri.getTc(),musteri.getAd(),musteri.getSoyad(),musteri.getSifre(),musteri.getT_tc_no()};
                
                model.addRow(degerler); //metodu object dizi aldıgından degerler dizisini object tanımladık
            }
        }
        else{
               //degerler musteri goruntuleden geleceğinden orta kontrol yapılıyor izin kontorlu bir daha etmeyelim
        }
        
    }
    
    public void adresGoruntule(){
        
        guncelleModelAdres.setRowCount(0);
        
        ArrayList <Madres> adresler = new ArrayList <Madres>();
        
        adresler = temsilci.getOwnAdresiList(); // databaseeden gelen musterileri aldık
        
        if(adresler != null){
            
            for(Madres adres : adresler){
                Object [] degerler ={adres.getId(),adres.getAdres(),adres.getTc_no()};
                
                guncelleModelAdres.addRow(degerler); //metodu object dizi aldıgından degerler dizisini object tanımladık
            }
        }
        else{
               //degerler musteri goruntuleden geleceğinden orta kontrol yapılıyor izin kontorlu bir daha etmeyelim
        }
        
    }
    
    public void telefonGoruntule(){
        
        guncelleModelTelefon.setRowCount(0);
        
        ArrayList <Mtelefon> telefonlar = new ArrayList <Mtelefon>();
        
        telefonlar = temsilci.getOwnTelefonList(); // databaseeden gelen musterileri aldık
        
        if(telefonlar != null){
            
            for(Mtelefon telefon : telefonlar){
                Object [] degerler ={telefon.getId(),telefon.getTel_no(),telefon.getTc_no()};
                
                guncelleModelTelefon.addRow(degerler); //metodu object dizi aldıgından degerler dizisini object tanımladık
            }
        }
        else{
               //degerler musteri goruntuleden geleceğinden orta kontrol yapılıyor izin kontorlu bir daha etmeyelim
        }
        
    }
    
    public void epostaGoruntule(){
        
        guncelleModelEposta.setRowCount(0);
        
        ArrayList <Meposta> epostalar = new ArrayList <Meposta>();
        
        epostalar = temsilci.getOwnEpostaList(); // databaseeden gelen musterileri aldık
        
        if(epostalar != null){
            
            for(Meposta eposta : epostalar){
                Object [] degerler ={eposta.getId(),eposta.getEposta(),eposta.getTc_no()};
                
                guncelleModelEposta.addRow(degerler); //metodu object dizi aldıgından degerler dizisini object tanımladık
            }
        }
        else{
               //degerler musteri goruntuleden geleceğinden orta kontrol yapılıyor izin kontorlu bir daha etmeyelim
        }
        
    }
    
    public void islemGoruntule(){
        
        islemModel.setRowCount(0);
        
        ArrayList <Islem> islemler = new ArrayList <Islem>();
        
        islemler = temsilci.getIslemList(); // databasen gelen degerlerimizi aldık
        
        if(islemler != null){
            
            for(Islem islem : islemler){
                Object [] degerler ={islem.getIno(),islem.getKaynak(),islem.getHedef(),islem.getIslem(),islem.getTutar(),islem.getKbakiye(),islem.getHbakiye(),islem.getTarih()};
                
                islemModel.addRow(degerler); //metodu object dizi aldıgından degerler dizisini object tanımladık
            }
        }
        
    }
    
    public void islemMiktarGoruntule(String miktar){
        
         islemModel.setRowCount(0);
        
        ArrayList <Islem> islemler = new ArrayList <Islem>();
        
        islemler = temsilci.getIslemMiktarList(miktar); // databasen gelen degerlerimizi aldık
        
        if(islemler != null){
            
            for(Islem islem : islemler){
                Object [] degerler ={islem.getIno(),islem.getKaynak(),islem.getHedef(),islem.getIslem(),islem.getTutar(),islem.getKbakiye(),islem.getHbakiye(),islem.getTarih()};
                
                islemModel.addRow(degerler); //metodu object dizi aldıgından degerler dizisini object tanımladık
            }
        }
        
        
    }
    
    
    public void islemGoruntule2(){
        
        islemModel2.setRowCount(0);
        
        ArrayList <Islem> islemler = new ArrayList <Islem>();
        
        islemler = temsilci.getIslemList2(); // databasen gelen degerlerimizi aldık
        
        if(islemler != null){
            
            for(Islem islem : islemler){
                Object [] degerler ={islem.getIno(),islem.getKaynak(),islem.getIslem(),islem.getTutar(),islem.getKbakiye(),islem.getTarih()};
                
                islemModel2.addRow(degerler); //metodu object dizi aldıgından degerler dizisini object tanımladık
            }
        }
        
    }
    
    public void islemMiktarGoruntule2(String miktar){
        
         islemModel2.setRowCount(0);
        
        ArrayList <Islem> islemler = new ArrayList <Islem>();
        
        islemler = temsilci.getIslemMiktarList2(miktar); // databasen gelen degerlerimizi aldık
        
        if(islemler != null){
            
            for(Islem islem : islemler){
                Object [] degerler ={islem.getIno(),islem.getKaynak(),islem.getIslem(),islem.getTutar(),islem.getKbakiye(),islem.getTarih()};
                
                islemModel2.addRow(degerler); //metodu object dizi aldıgından degerler dizisini object tanımladık
            }
        }
        
        
    }
    
    
    
    public void talepGoruntule(){
        
        talepModel.setRowCount(0);
        
        ArrayList <Talep> talepler = new ArrayList <Talep>();
        
        talepler = temsilci.getTalepList(); // databasen gelen degerlerimizi aldık
        
        if(talepler != null){
            
            for(Talep talep : talepler){
                Object [] degerler ={talep.getId(),talep.getTc_no(),talep.getIad() , talep.getOnay()};
                
                talepModel.addRow(degerler); //metodu object dizi aldıgından degerler dizisini object tanımladık
            }
        }
        
    }
    
    public void tarihGoruntule(){
        
        String tarih = temsilci.getNowDate();
        if(tarih!=null)
        lbl_temsilci_tarih.setText(tarih);
    }
    
    public void krediGoruntule(){
        
        krediModel.setRowCount(0);
        
        ArrayList <Kredi> krediler = new ArrayList <Kredi>();
        
        krediler = temsilci.getOwnKrediList(); // databasen gelen degerlerimizi aldık
        
        if(krediler != null){
            
            for(Kredi kredi : krediler){
                Object [] degerler ={kredi.getMiktar(),kredi.getHno(),kredi.getAylik(),kredi.getAfaiz(),kredi.getAgfaiz(),kredi.getKalan_nborc(),kredi.getOdurum(),kredi.getKalan_gun(),kredi.getTarih(),kredi.getMtc()};
                
                krediModel.addRow(degerler); //metodu object dizi aldıgından degerler dizisini object tanımladık
            }
        }
        
    }
    

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(temsilciGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(temsilciGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(temsilciGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(temsilciGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new temsilciGUI(temsilci).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_tamsilci_talep_reddet;
    private javax.swing.JButton btn_temsilci_duzenle;
    private javax.swing.JButton btn_temsilci_islem;
    private javax.swing.JButton btn_temsilci_islem2;
    private javax.swing.JButton btn_temsilci_kredi_tablosu_guncelle;
    private javax.swing.JButton btn_temsilci_muster_ekle;
    private javax.swing.JButton btn_temsilci_musteri_eposta;
    private javax.swing.JButton btn_temsilci_musteri_sil;
    private javax.swing.JButton btn_temsilci_musteri_telefob;
    private javax.swing.JButton btn_temsilci_talep_onay;
    private javax.swing.JButton btn_tesilci_musteri_adres;
    private javax.swing.JComboBox<String> combo_temsilci_islem;
    private javax.swing.JComboBox<String> combo_temsilci_islem2;
    private javax.swing.JTextField fld_temsilci_ad_ekle;
    private javax.swing.JTextField fld_temsilci_musteri_adres;
    private javax.swing.JTextField fld_temsilci_musteri_adres_id;
    private javax.swing.JTextField fld_temsilci_musteri_adres_tc;
    private javax.swing.JTextField fld_temsilci_musteri_eposta;
    private javax.swing.JTextField fld_temsilci_musteri_eposta_id;
    private javax.swing.JTextField fld_temsilci_musteri_eposta_tc;
    private javax.swing.JTextField fld_temsilci_musteri_telefon;
    private javax.swing.JTextField fld_temsilci_musteri_telefon_id;
    private javax.swing.JTextField fld_temsilci_musteri_telefon_tc;
    private javax.swing.JTextField fld_temsilci_soyad_ekle;
    private javax.swing.JTextField fld_temsilci_talep_iad;
    private javax.swing.JTextField fld_temsilci_talep_id;
    private javax.swing.JTextField fld_temsilci_talep_onay;
    private javax.swing.JTextField fld_temsilci_talep_tc_no;
    private javax.swing.JTextField fld_temsilci_tc_no_ekle;
    private javax.swing.JTextField fld_temsilci_tc_no_sil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_temsilci_tarih;
    private javax.swing.JTable temsilci_guncelle_adres_table;
    private javax.swing.JTable temsilci_guncelle_eposta_table;
    private javax.swing.JTable temsilci_guncelle_telefon_table;
    private javax.swing.JTable temsilci_islem22_tablo;
    private javax.swing.JTable temsilci_islem_tablo;
    private javax.swing.JTable temsilci_kredi_table;
    private javax.swing.JTable temsilci_musteri_table;
    private javax.swing.JTable temsilci_talep_table;
    private javax.swing.JButton temsilci_talep_yenile;
    // End of variables declaration//GEN-END:variables
}
